#Ran before pipeline
Resources:
  CodePipelineBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub security-deployment-artifacts-${StageParameter}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
                
Parameters:
  StageParameter:
    Description: Enter stage environment you are creating resource for. Default is matsonlabs
    Type: String
    Default: matsonlabs
    AllowedValues:
      - mlscDev
      - mlscPreprod
      - mlscProd
      - mdaas
      - infosec
      - matsonlabs
      - qa
      - dr
      - org
      - china
      - workspaces
      - dev
      - pp
      - prod

Outputs:
  ArtifactStoreS3:
    Description: The s3 bucket for codepipeline artifact stores
    Value: !Ref CodePipelineBucket
    Export:
      Name: SecurityDeploymentBucketNamex

  ArtifactStoreArn:
    Description: The arn value of the s3 bucket
    Value: !GetAtt CodePipelineBucket.Arn
    Export:
      Name: SecurityDeploymentBucketArnx