Resources:
  ConfigPermissionToCallLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !ImportValue checkSGPortIngressArn
      Action: "lambda:InvokeFunction"
      Principal: "config.amazonaws.com"
  ConfigRuleCheckSGPortIngress: 
    Type: AWS::Config::ConfigRule
    Properties: 
      ConfigRuleName: !Sub ${Service}CheckSGPortIngress
      Scope:
        ComplianceResourceTypes: 
          - "AWS::EC2::SecurityGroup"
      Source: 
        Owner: "CUSTOM_LAMBDA"
        SourceDetails: 
          - 
            EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
        SourceIdentifier: !ImportValue checkSGPortIngressArn

Parameters:
  Service:
    Description: Name of the service you are deploying, name will be used to reference in IAM role and policy
    Type: String