service: ${env:SERVICE}TagSGTermination

custom:
  stage: ${opt:stage, 'matsonlabs'}

provider:
  name: aws
  stackName: ${self:service}Lambdas
  runtime: python3.6
  memorySize: 128
  timeout: 180
  stage: ${self:custom.stage}
  region: us-west-2
  deploymentBucket:
    name: security-deployment-artifacts-${self:provider.stage}

package:
  individually: true
  exclude:
    - "**/*"  # quotes(") are needed

functions:
  tagSGTermination:
    handler: tag_sg_termination.lambda_handler
    package:
      include:
        - "tag_sg_termination.py"
        - "slack_alert.py"
    name: ${self:service}_tag_sg_termination
    role: CheckRole
    environment:
      SERVICE: ${self:service}
      REGION: ${self:provider.region}
      ACCOUNT_ALIAS: ${env:ACCOUNT_ALIAS}

  terminateTagged:
    handler: terminate_tagged.lambda_handler
    package:
      include:
        - "terminate_tagged.py"
        - "slack_alert.py"
    name: ${self:service}_terminate_tagged
    role: DeleteRole
    environment:
      SERVICE: ${self:service}
      REGION: ${self:provider.region}
      ACCOUNT_ALIAS: ${env:ACCOUNT_ALIAS}
    events:
      - schedule: cron(0 7 * * ? *) # 10PM Oakland

resources:
  Resources:
# Permissions for tag_sg_termination.py
    CheckRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: ${self:functions.tagSGTermination.name}LambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

    CheckDefaultPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: ${self:functions.tagSGTermination.name}LambdaPolicy
        Roles:
          - Ref: "CheckRole"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: CreateLogStream
              Effect: Allow
              Action:
                - logs:CreateLogStream
              Resource:
                - arn:aws:logs:${self:provider.region}:${env:ACCOUNT_ID}:log-group:/aws/lambda/${self:functions.tagSGTermination.name}:*
            - Sid: PutLogEvents
              Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:${self:provider.region}:${env:ACCOUNT_ID}:log-group:/aws/lambda/${self:functions.tagSGTermination.name}:*:*
      DependsOn:
        - CheckRole

    CheckPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: ${self:functions.tagSGTermination.name}LambdaExecutionPolicy
        Roles:
          - Ref: "CheckRole"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: CheckExecution
              Effect: Allow
              Action:
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeSecurityGroups
              - lambda:ListFunctions
              - config:PutEvaluations
              Resource: "*"
            - Sid: CreateTags
              Effect: Allow
              Action:
              - ec2:CreateTags
              Resource: "arn:aws:ec2:${self:provider.region}:${env:ACCOUNT_ID}:security-group/*"
      DependsOn:
        - CheckRole

# Permissions for terminate_tagged.py
    DeleteRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: ${self:functions.terminateTagged.name}LambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

    DeleteDefaultPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: ${self:functions.terminateTagged.name}LogPolicy
        Roles:
          - Ref: "DeleteRole"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: CreateLogStream
              Effect: Allow
              Action:
                - logs:CreateLogStream
              Resource:
                - arn:aws:logs:${self:provider.region}:${env:ACCOUNT_ID}:log-group:/aws/lambda/${self:functions.terminateTagged.name}:*
            - Sid: PutLogEvents
              Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:${self:provider.region}:${env:ACCOUNT_ID}:log-group:/aws/lambda/${self:functions.terminateTagged.name}:*:*
      DependsOn:
        - DeleteRole  

    DeletePolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: ${self:functions.terminateTagged.name}ExecutionPolicy
        Roles:
          - Ref: "DeleteRole"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: DescribeTags
              Effect: Allow
              Action:
              - ec2:DescribeTags
              Resource: "*"
            - Sid: DeleteSgs
              Effect: Allow
              Action:
              - ec2:DeleteSecurityGroup
              Resource: "arn:aws:ec2:${self:provider.region}:${env:ACCOUNT_ID}:security-group/*"
            - Sid: CreateTags
              Effect: Allow
              Action:
              - ec2:CreateTags
              Resource: "arn:aws:ec2:${self:provider.region}:${env:ACCOUNT_ID}:security-group/*"
      DependsOn:
        - DeleteRole

# KMS and SSM for slack alerts, used by both
    DefaultKMSPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: ${self:service}SSMPolicy
        Roles:
          - Ref: "CheckRole"
          - Ref: "DeleteRole"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowDecryptSSM
              Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
                - ssm:GetParameters
              Resource:
                - Fn::ImportValue: SecurityErrorsKMSKeyArn
                - arn:aws:ssm:${self:provider.region}:${env:ACCOUNT_ID}:parameter/SECURITY_ERRORS*
      DependsOn:
        - CheckRole
        - DeleteRole

  Outputs:
    TagSGTerminationLambdaFunctionQualifiedArn:
      Export:
        Name: tagSGTerminationArn

    TerminateTaggedLambdaFunctionQualifiedArn:
      Export:
        Name: terminateTaggedArn

    ServerlessDeploymentBucketName:
      Export:
        Name: ${self:service}Bucket